import 'cleanup_rule.dart';

const builtinCleanupRules = <CleanupRule>[
  CleanupRule(
    id: 'windows-temp',
    name: 'Windows 临时文件',
    description: '系统临时目录中的文件通常可以重新生成。',
    platform: CleanupPlatform.windows,
    scope: '%LOCALAPPDATA%',
    matcherType: CleanupMatcherType.exactPath,
    matcherValue: '%LOCALAPPDATA%/Temp',
    risk: CleanupRisk.safe,
    action: CleanupActionType.moveToTrash,
    profileId: 'windows-system',
    defaultSelected: true,
  ),
  CleanupRule(
    id: 'windows-npm-cache',
    name: 'npm 下载缓存',
    description: 'npm 会在需要时重新下载缓存内容。',
    platform: CleanupPlatform.windows,
    scope: '%LOCALAPPDATA%',
    matcherType: CleanupMatcherType.exactPath,
    matcherValue: '%LOCALAPPDATA%/npm-cache',
    risk: CleanupRisk.safe,
    action: CleanupActionType.moveToTrash,
    profileId: 'windows-development',
    defaultSelected: true,
  ),
  CleanupRule(
    id: 'windows-vscode-ipch',
    name: 'VS Code C/C++ IntelliSense 缓存',
    description: '删除后 VS Code 会重新建立 IntelliSense 索引。',
    platform: CleanupPlatform.windows,
    scope: '%LOCALAPPDATA%',
    matcherType: CleanupMatcherType.exactPath,
    matcherValue: '%LOCALAPPDATA%/Microsoft/vscode-cpptools/ipch',
    risk: CleanupRisk.safe,
    action: CleanupActionType.moveToTrash,
    profileId: 'windows-development',
    defaultSelected: true,
  ),
  CleanupRule(
    id: 'windows-pnpm-store',
    name: 'pnpm Store',
    description: '建议使用 pnpm store prune，由 pnpm 判断哪些包可以移除。',
    platform: CleanupPlatform.windows,
    scope: '%LOCALAPPDATA%',
    matcherType: CleanupMatcherType.exactPath,
    matcherValue: '%LOCALAPPDATA%/pnpm',
    risk: CleanupRisk.rebuildable,
    action: CleanupActionType.externalInstructions,
    profileId: 'windows-development',
  ),
  CleanupRule(
    id: 'macos-user-cache',
    name: '用户缓存目录',
    description: 'macOS 用户缓存，建议确认具体应用后再处理。',
    platform: CleanupPlatform.macos,
    scope: r'$HOME',
    matcherType: CleanupMatcherType.exactPath,
    matcherValue: r'$HOME/Library/Caches',
    risk: CleanupRisk.caution,
    action: CleanupActionType.reportOnly,
    profileId: 'macos-user-cache',
  ),
  CleanupRule(
    id: 'linux-user-cache',
    name: '用户缓存目录',
    description: 'Linux 用户缓存，先查看具体应用再决定是否清理。',
    platform: CleanupPlatform.linux,
    scope: r'$HOME',
    matcherType: CleanupMatcherType.exactPath,
    matcherValue: r'$HOME/.cache',
    risk: CleanupRisk.caution,
    action: CleanupActionType.reportOnly,
    profileId: 'linux-user-cache',
  ),
];
