// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.5.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/hybrid_search_api.dart';
import 'api/project_api.dart';
import 'api/public.dart';
import 'api/scanner_api.dart';
import 'api/simple.dart';
import 'api/tools_api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'hybrid_search.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'project.dart';
import 'scanner/compare_result.dart';
import 'scanner/event.dart';
import 'scanner/file.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<CompareResult> dco_decode_StreamSink_compare_result_Sse(
      dynamic raw);

  @protected
  RustStreamSink<HybridSearchDetail>
      dco_decode_StreamSink_hybrid_search_detail_Sse(dynamic raw);

  @protected
  RustStreamSink<ProjectDetail> dco_decode_StreamSink_project_detail_Sse(
      dynamic raw);

  @protected
  RustStreamSink<ResEvent> dco_decode_StreamSink_res_event_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  CompareEvent dco_decode_box_autoadd_compare_event(dynamic raw);

  @protected
  DoneEvent dco_decode_box_autoadd_done_event(dynamic raw);

  @protected
  ResEvent dco_decode_box_autoadd_res_event(dynamic raw);

  @protected
  ScannerEvent dco_decode_box_autoadd_scanner_event(dynamic raw);

  @protected
  CompareEvent dco_decode_compare_event(dynamic raw);

  @protected
  CompareResult dco_decode_compare_result(dynamic raw);

  @protected
  DoneEvent dco_decode_done_event(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  File dco_decode_file(dynamic raw);

  @protected
  HybridSearchDetail dco_decode_hybrid_search_detail(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<File> dco_decode_list_file(dynamic raw);

  @protected
  List<List<File>> dco_decode_list_list_file(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  OperationResult dco_decode_operation_result(dynamic raw);

  @protected
  ProjectDetail dco_decode_project_detail(dynamic raw);

  @protected
  ResEvent dco_decode_res_event(dynamic raw);

  @protected
  ScannerEvent dco_decode_scanner_event(dynamic raw);

  @protected
  SearchType dco_decode_search_type(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<CompareResult> sse_decode_StreamSink_compare_result_Sse(
      SseDeserializer deserializer);

  @protected
  RustStreamSink<HybridSearchDetail>
      sse_decode_StreamSink_hybrid_search_detail_Sse(
          SseDeserializer deserializer);

  @protected
  RustStreamSink<ProjectDetail> sse_decode_StreamSink_project_detail_Sse(
      SseDeserializer deserializer);

  @protected
  RustStreamSink<ResEvent> sse_decode_StreamSink_res_event_Sse(
      SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  CompareEvent sse_decode_box_autoadd_compare_event(
      SseDeserializer deserializer);

  @protected
  DoneEvent sse_decode_box_autoadd_done_event(SseDeserializer deserializer);

  @protected
  ResEvent sse_decode_box_autoadd_res_event(SseDeserializer deserializer);

  @protected
  ScannerEvent sse_decode_box_autoadd_scanner_event(
      SseDeserializer deserializer);

  @protected
  CompareEvent sse_decode_compare_event(SseDeserializer deserializer);

  @protected
  CompareResult sse_decode_compare_result(SseDeserializer deserializer);

  @protected
  DoneEvent sse_decode_done_event(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  File sse_decode_file(SseDeserializer deserializer);

  @protected
  HybridSearchDetail sse_decode_hybrid_search_detail(
      SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<File> sse_decode_list_file(SseDeserializer deserializer);

  @protected
  List<List<File>> sse_decode_list_list_file(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  OperationResult sse_decode_operation_result(SseDeserializer deserializer);

  @protected
  ProjectDetail sse_decode_project_detail(SseDeserializer deserializer);

  @protected
  ResEvent sse_decode_res_event(SseDeserializer deserializer);

  @protected
  ScannerEvent sse_decode_scanner_event(SseDeserializer deserializer);

  @protected
  SearchType sse_decode_search_type(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_compare_result_Sse(
      RustStreamSink<CompareResult> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_hybrid_search_detail_Sse(
      RustStreamSink<HybridSearchDetail> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_project_detail_Sse(
      RustStreamSink<ProjectDetail> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_res_event_Sse(
      RustStreamSink<ResEvent> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_compare_event(
      CompareEvent self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_done_event(
      DoneEvent self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_res_event(
      ResEvent self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_scanner_event(
      ScannerEvent self, SseSerializer serializer);

  @protected
  void sse_encode_compare_event(CompareEvent self, SseSerializer serializer);

  @protected
  void sse_encode_compare_result(CompareResult self, SseSerializer serializer);

  @protected
  void sse_encode_done_event(DoneEvent self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_file(File self, SseSerializer serializer);

  @protected
  void sse_encode_hybrid_search_detail(
      HybridSearchDetail self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_file(List<File> self, SseSerializer serializer);

  @protected
  void sse_encode_list_list_file(
      List<List<File>> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_operation_result(
      OperationResult self, SseSerializer serializer);

  @protected
  void sse_encode_project_detail(ProjectDetail self, SseSerializer serializer);

  @protected
  void sse_encode_res_event(ResEvent self, SseSerializer serializer);

  @protected
  void sse_encode_scanner_event(ScannerEvent self, SseSerializer serializer);

  @protected
  void sse_encode_search_type(SearchType self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
