// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.5.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../project.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Stream<ProjectDetail> projectScanStream() =>
    RustLib.instance.api.crateApiProjectApiProjectScanStream();

Future<void> projectScan({required String p}) =>
    RustLib.instance.api.crateApiProjectApiProjectScan(p: p);

Future<void> projectScanReallyFast({required String p}) =>
    RustLib.instance.api.crateApiProjectApiProjectScanReallyFast(p: p);
